### ISSUE TITLE
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

### ISSUE THREAD

**Issue by hly666666** [minghaochen/chatglm3-base-tuning#5]
Traceback (most recent call last):
  File "train.py", line 52, in <module>
    trainer.train()
  File "/root/autodl-tmp/chatglm3-base-tuning/trainer.py", line 25, in train
    self.model_engine.train(data_module=self.data_module)
  File "/root/autodl-tmp/chatglm3-base-tuning/ChatGLM_model_engine.py", line 41, in train
    trainer.train()
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/peft/peft_model.py", line 977, in forward
    return self.base_model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/peft/tuners/tuners_utils.py", line 106, in forward
    return self.model.forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modelbase/modeling_chatglm.py", line 938, in forward
    transformer_outputs = self.transformer(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modelbase/modeling_chatglm.py", line 820, in forward
    full_attention_mask = self.get_masks(input_ids, past_key_values, padding_mask=attention_mask)
  File "/root/.cache/huggingface/modules/transformers_modules/modelbase/modeling_chatglm.py", line 691, in get_masks
    full_attention_mask -= padding_mask.unsqueeze(-1) - 1
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

**Comment by minghaochen** [comment]
看close的issue的第一条哈

**Comment by minghaochen** [comment]
https://github.com/minghaochen/chatglm3-base-tuning/issues/1#issuecomment-1789948566
