### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by makeukus** [minghaochen/chatglm3-base-tuning#7]
ModuleNotFoundError: No module named 'transformers_modules.'
也安装不了

**Comment by makeukus** [comment]
D:\ProgramData\anaconda3\envs\llama_factory\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
TrainingConfig(model_name='./chatglm3-6b-base', data_path='formatted_samples.json', output_dir='./trained_model', training_recipe='lora', optim='paged_adamw_8bit', batch_size=4, gradient_accumulation_steps=1, n_epochs=5, weight_decay=0.0, learning_rate=0.0001, max_grad_norm=0.3, gradient_checkpointing=True, do_train=True, lr_scheduler_type='cosine', warmup_ratio=0.03, logging_steps=1, group_by_length=True, save_strategy='epoch', save_total_limit=3, fp16=False, tokenizer_type='llama', trust_remote_code=True, compute_dtype=torch.float16, max_tokens=4096, do_eval=True, evaluation_strategy='epoch', use_auth_token=False, use_fast=False, bits=4, double_quant=True, quant_type='nf4', lora_r=64, lora_alpha=16, lora_dropout=0.05)
2023-11-12 19:24:43,555 - INFO - Event captured: start-training with properties: {}
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\ChatGLM3\chatglm3-base-tuning-master\chatglm3-base-tuning-master\train.py", line 52, in <module>
    trainer.train()
  File "D:\BaiduNetdiskDownload\ChatGLM3\chatglm3-base-tuning-master\chatglm3-base-tuning-master\trainer.py", line 17, in train
    self.model_engine.prepare_model_for_training()
  File "D:\BaiduNetdiskDownload\ChatGLM3\chatglm3-base-tuning-master\chatglm3-base-tuning-master\ChatGLM_model_engine.py", line 49, in prepare_model_for_training
    self.model = transformers.AutoModelForCausalLM.from_pretrained(
  File "D:\ProgramData\anaconda3\envs\llama_factory\lib\site-packages\transformers\models\auto\auto_factory.py", line 456, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "D:\ProgramData\anaconda3\envs\llama_factory\lib\site-packages\transformers\models\auto\configuration_auto.py", line 953, in from_pretrained
    config_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "D:\ProgramData\anaconda3\envs\llama_factory\lib\site-packages\transformers\dynamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "D:\ProgramData\anaconda3\envs\llama_factory\lib\site-packages\transformers\dynamic_module_utils.py", line 164, in get_class_in_module
    module = importlib.import_module(module_path)
  File "D:\ProgramData\anaconda3\envs\llama_factory\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.'

**Comment by minghaochen** [comment]
transformers库的问题吧
pip install protobuf transformers==4.30.2 cpm_kernels torch>=2.0 gradio mdtex2html sentencepiece accelerate
